export const colors = {
  brandMint: "#F3FFE9",
  brandGreen: "#1E4B2F",
  brandBorder: "#6BB36F",
  brandOrange: "#F69A4C",
  brandBlue: "#B8EDFF",
  textBlack: "#111111",
  textGold: "#FFB659",
  textBlue: "#60D5FF",
  textGreen: "#7AC3A5",
  nutriOrange: "#FFB659",
  nutriBlue: "#60D5FF",
  nutriYellow: "#FFD23D",
  nutriGreen: "#7CFF85",
  nutriPink: "#FF95CD",
  scoreGreen: "#DDFFDE",
  scorePink: "#FFDDF2",
  scoreOrange: "#FFF0DD",
  scoreBlue: "#EFFBFF",
  active: "#EEF9E8",
  white: "#FFFFFF",
} as const
